#!/usr/bin/env python3

print("=" * 60)
print("Pi Schedule Display - Deployment Information")
print("=" * 60)
print()
print("This project is designed to run on a Raspberry Pi with the")
print("Waveshare 1.44\" LCD HAT hardware attached.")
print()
print("It cannot run in a cloud environment because it requires:")
print("  - Raspberry Pi GPIO pins")
print("  - SPI interface for the LCD display")
print("  - Physical joystick and buttons")
print("  - Direct hardware access")
print()
print("To deploy this project:")
print()
print("1. Transfer these files to your Raspberry Pi:")
print("   scp -r . pi@raspberrypi.local:/home/pi/schedule-display")
print()
print("2. On the Pi, run the installation script:")
print("   cd /home/pi/schedule-display")
print("   ./install.sh")
print()
print("3. Configure your schedule:")
print("   python3 configure_schedule.py")
print()
print("4. Run the application:")
print("   ./start.sh")
print()
print("5. (Optional) Enable auto-start on boot:")
print("   sudo cp schedule-display.service /etc/systemd/system/")
print("   sudo systemctl enable schedule-display.service")
print()
print("See DEPLOYMENT.md for detailed instructions.")
print("=" * 60)
