#!/usr/bin/env python3
"""
Example demonstration of the AI configuration workflow
Shows what the AI would extract from a schedule image
"""

import json

# This is an example of what the AI would extract from the sample schedule image
example_analysis = {
    "school_start": "09:05",
    "school_end": "15:20",
    "num_periods": 6,
    "period_times": {
        "1": "09:25",
        "2": "10:20",
        "3": "11:15",
        "4": "12:40",
        "5": "13:35",
        "6": "14:30"
    },
    "period_length": 50,
    "passing_time": 5,
    "period_names": {
        "1": "Math",
        "2": "English",
        "3": "Science",
        "4": "History",
        "5": "Spanish",
        "6": "Art"
    },
    "has_ab_day": True,
    "a_day_periods": {
        "1": "Math",
        "2": "English",
        "3": "Science",
        "4": "History",
        "5": "Spanish",
        "6": "Art"
    },
    "b_day_periods": {
        "1": "Math",
        "2": "English",
        "3": "Science",
        "4": "PE",
        "5": "Spanish",
        "6": "Music"
    },
    "has_advisory": True,
    "advisory_start": "09:05",
    "advisory_length": 15,
    "advisory_days": ["m", "t"],
    "has_lunch": True,
    "lunch_start": "12:05",
    "lunch_end": "12:35",
    "uncertain_items": [],
    "notes": "Standard A/B day schedule with advisory on Monday and Tuesday"
}

# Example user inputs
example_user_inputs = {
    "use_24_hour": False,
    "timezone": "America/New_York",
    "canvas_enabled": True,
    "canvas_url": "https://school.instructure.com",
    "canvas_token": "",  # Can be set later on device
    "wifi_networks": [
        ["HomeWiFi", "password123"],
        ["SchoolWiFi", "student2024"]
    ],
    "time_sync_mode": "on_boot",
    "progress_bar_mode": "time_in_class"
}

def generate_config_preview():
    """Generate what the config.py would look like"""
    analysis = example_analysis
    inputs = example_user_inputs
    
    config = f"""# School Schedule Configuration
# Generated by Timagotchi AI Configurator

# Time format: "HH:MM" (24-hour format)
SCHOOL_START = "{analysis['school_start']}"
SCHOOL_END = "{analysis['school_end']}"
USE_24_HOUR = {inputs['use_24_hour']}

# Advisory period
ADVISORY_START = "{analysis['advisory_start']}"
ADVISORY_PERIOD = 0
advisory = "true"
advisorylength = "{analysis['advisory_length']}"
advisorydays = "{','.join(analysis['advisory_days'])}"
freetimedaus = "w,th,f"

# Period start times
PERIODS = {{
    {', '.join([f"{k}: \"{v}\"" for k, v in sorted(analysis['period_times'].items(), key=lambda x: int(x[0]))])}
}}

# Lunch information
LUNCH_START = "{analysis['lunch_start']}"
LUNCH_END = "{analysis['lunch_end']}"

# Period names
A_DAY_PERIODS = {{{', '.join([f"{k}: '{v}'" for k, v in sorted(analysis['a_day_periods'].items(), key=lambda x: int(x[0]))])}}}

B_DAY_PERIODS = {{{', '.join([f"{k}: '{v}'" for k, v in sorted(analysis['b_day_periods'].items(), key=lambda x: int(x[0]))])}}}

# Period lengths (in minutes)
PERIOD_LENGTH = {analysis['period_length']}
PASSING_TIME = {analysis['passing_time']}

# Additional settings
lunchlength = "30"
abday = "true"
AB_DAY_MODE = "auto"
MANUAL_AB_DAY = "a"

# WiFi Networks
WIFI_NETWORKS = [
    {', '.join([f'("{ssid}", "{pwd}")' for ssid, pwd in inputs['wifi_networks']])}
]

# Time Sync Settings
TIME_SYNC_MODE = "{inputs['time_sync_mode']}"
TIME_SYNC_INTERVAL = 6
TIMEZONE = "{inputs['timezone']}"

# Progress Bar Settings
PROGRESS_BAR_MODE = "{inputs['progress_bar_mode']}"
"""
    return config

def show_workflow():
    """Show the complete AI configuration workflow"""
    print("=" * 80)
    print("AI-POWERED SCHEDULE CONFIGURATION WORKFLOW EXAMPLE")
    print("=" * 80)
    print()
    
    print("STEP 1: User uploads schedule photo")
    print("-" * 80)
    print("Sample image: /tmp/test_schedules/sample_schedule.png")
    print("Contains: A/B day schedule with 6 periods, advisory, and lunch")
    print()
    
    print("STEP 2: AI analyzes the image")
    print("-" * 80)
    print("Gemini Vision API processes the image and extracts:")
    print(json.dumps(example_analysis, indent=2))
    print()
    
    print("STEP 3: User reviews and provides additional info")
    print("-" * 80)
    print("User confirms AI analysis is correct")
    print("User adds:")
    print("  - Canvas LMS URL: " + example_user_inputs['canvas_url'])
    print("  - WiFi networks: " + str(len(example_user_inputs['wifi_networks'])) + " networks")
    print("  - Timezone: " + example_user_inputs['timezone'])
    print("  - Time format: " + ("24-hour" if example_user_inputs['use_24_hour'] else "12-hour"))
    print()
    
    print("STEP 4: AI generates config.py")
    print("-" * 80)
    config = generate_config_preview()
    print(config)
    print()
    
    print("STEP 5: User submits to device")
    print("-" * 80)
    print("User enters device pairing code: 12345")
    print("Configuration sent to device via pairing API")
    print("Device receives config and restarts")
    print()
    
    print("=" * 80)
    print("RESULT: Fully configured Timagotchi in under 5 minutes!")
    print("=" * 80)
    print()
    
    print("Benefits of AI Configuration:")
    print("  ✓ No manual typing of times and names")
    print("  ✓ Automatically detects A/B days")
    print("  ✓ Identifies advisory and lunch periods")
    print("  ✓ Extracts all period information")
    print("  ✓ Asks clarifying questions for uncertain items")
    print("  ✓ Interactive chat for any questions")
    print()
    
    print("Compare to Manual Configuration:")
    print("  Manual: 15-20 minutes of form filling")
    print("  AI: 2-3 minutes (photo + review)")
    print()

def show_api_example():
    """Show example API calls"""
    print("=" * 80)
    print("API ENDPOINT EXAMPLES")
    print("=" * 80)
    print()
    
    print("POST /api/analyze-schedule")
    print("-" * 80)
    print("Request:")
    print("  multipart/form-data with 'image' file")
    print()
    print("Response:")
    print(json.dumps({
        "status": "success",
        "analysis": example_analysis,
        "has_uncertainties": False
    }, indent=2))
    print()
    
    print("POST /api/ask-question")
    print("-" * 80)
    print("Request:")
    print(json.dumps({
        "question": "What time does lunch start?",
        "context": {"lunch_start": "12:05", "lunch_end": "12:35"}
    }, indent=2))
    print()
    print("Response:")
    print(json.dumps({
        "status": "success",
        "answer": "Lunch starts at 12:05 PM and ends at 12:35 PM, giving you a 30-minute lunch period."
    }, indent=2))
    print()
    
    print("POST /api/generate-config")
    print("-" * 80)
    print("Request:")
    print(json.dumps({
        "analysis": {"school_start": "09:05", "num_periods": 6},
        "user_inputs": {"timezone": "America/New_York"}
    }, indent=2))
    print()
    print("Response:")
    print(json.dumps({
        "status": "success",
        "config_content": "# School Schedule Configuration\n..."
    }, indent=2))
    print()

if __name__ == '__main__':
    import sys
    
    if len(sys.argv) > 1 and sys.argv[1] == '--api':
        show_api_example()
    else:
        show_workflow()
        print()
        print("Run with --api flag to see API endpoint examples")
